# Generated by Django 5.0 on 2024-01-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
